version: "1"
services:

  MysqlIA:
    image: mysql
    networks:
      IAnet:
        aliases:
          - MysqlIA
    container_name: MysqlIA
    volumes:
      - "mysqlData:/var/lib/mysql"
      - "mysqlConf:/etc/mysql/conf.d"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  IA1:
    image: openjdk
    networks:
      IAnet:
        aliases:
          - IA1
    container_name: IA1
    depends_on:
      - MysqlIA
    volumes:
      - "javaApps:/usr/apps"
      - "ImageDB:/usr/ImageDB"
    ports:
      - "9001:8080"
    command: java -jar /usr/apps/ImageAnnotation.jar

  IA2:
    image: openjdk
    networks:
      IAnet:
        aliases:
          - IA2
    container_name: IA2
    depends_on:
      - MysqlIA
    volumes:
      - "javaApps:/usr/apps"
      - "ImageDB:/usr/ImageDB"
    ports:
      - "9002:8080"
    command: java -jar /usr/apps/ImageAnnotation.jar

  IA3:
    image: openjdk
    networks:
      IAnet:
        aliases:
          - IA3
    container_name: IA3
    depends_on:
      - MysqlIA
    volumes:
      - "javaApps:/usr/apps"
      - "ImageDB:/usr/ImageDB"
    ports:
      - "9003:8080"
    command: java -jar /usr/apps/ImageAnnotation.jar

  NginxIA:
    image: nginx
    networks:
      IAnet:
        aliases:
          - NginxIA
    container_name: NginxIA
    depends_on:
      - IA1
      - IA2
      - IA3
    volumes:
      - "nginxHtml:/usr/share/nginx/html"
      - "nginxConf:/etc/nginx/conf.d"
    ports:
      - "8080:80"
      - "8081:8081"

networks:
  IAnet:
    driver: bridge

volumes:
  javaApps:
  ImageDB:
  mysqlData:
  mysqlConf:
  nginxHtml:
  nginxConf:
